---
stages:
  - build
  - deploy

build:
  image: harbor.one.com/standard-images/ci/docker-buildkit:jammy-rootless
  when: manual
  tags:
    - k8s-large
  stage: build
  script:
    - harbor-login
    - docker_build . --tag $HARBOR_REGISTRY_PREFIX/devin-dashboard:$CI_COMMIT_SHORT_SHA

.deploy-template:
  image: harbor.one.com/standard-images/ci/kubectl:focal-rootless
  when: manual
  tags:
    - k8s-small
  stage: deploy
  dependencies: [build]
  script:
    - kubectl-setup
    - ./kubernetes/generate-yaml.sh | tee tmp-deployment.yaml
    - kubectl apply --dry-run=server --validate --filename tmp-deployment.yaml
    - kubectl apply --validate --filename tmp-deployment.yaml

deploy-production:
  extends: .deploy-template
  variables:
    RELEASE_ENVIRONMENT: production
  environment:
    name: mgmt1
