apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: api-secret
  namespace: devin-dashboard
spec:
  encryptedData:
    confluence_api_key: ""
    sonar_api_key: ""
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: api-secret
      namespace: devin-dashboard
---
