apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: api-secret
  namespace: devin-dashboard
spec:
  encryptedData:
    confluence_api_key: AgCzRNvGZLivU51US1xBD9IoGimufRxytNjJB0WUymelban5Xn9eDg/NhtXCIee64/AjQeTVRKJmrhcYd9Yrur0AaII3veR1zvWVeVUa4bfTTVVVIq3Mw0T4qA8PgFxJJYWEpB4SKg0td+QrebC/sRIxFvn1VntflxK2WrsdZ51nOsMktLwFOOhPVlmvQ895+gSb1Bzg8OqcjAKfK7ORS7tj3gsN152/WYNXyzANU3SDNZgFAcr1S3NwAbbknepncCRp59xUQIantXX9V68m4GyhMGUaHPZj4CzZHFz5YHYj3nnr0TFxg5IcSI+bHsNYrUfyaEOi+G7MEf9EMimKA+wee7mIU/p43XuqXb4ntUf7fSX6GCA3JyxNUnPn3A9fc55vuybSErsdjjjlBR67Pu7bok/MJWFM5qFdGJxH/mBXuR1O8vT4cXFW3aI6kJ8Ye9W6j4R9IAcM1qQ0bp0HBwgEO5gM64Jee/lQsJIxNnE7kXREVUctLySeRA1riBFc2bDNfnAtcLAG23STWPulYRjz8lT5Dyuq+dQplM8/JAyTEBLPKV1CuRDVO7tu8rtj6K07nPO6R5fb273o44h5EZPpNu4ZW6VZwd+2nHUnVw6THdeY03y8z4xo/a0+YeBwuaxV1LDv38T+HqUhA2xoViov8hWOudigxzIczxIi02RsU/O4geKB5jCnvhu1r4JVnfL5NzgnYr8riLcH7Op49xMGdMoyVdmKYfnee5hY/DP6N9rdGSGQxMJ8P1n+bQ04SZahEorjWtc9x/qjFpd4TTfmB2yOBdMWgn6u2mL0zcl93VdzG8IH8kP4XAcGgoEoXICMjJSqfMkTAr8mLm1/Ioxu79MaHPYWagv9g4VBqkIpfupEk38fZB0XmVsLGt3CBPIyPee6b2TK+6NJ36462g1vDqUfUF6oF9jmS+lA6YW43ZWQCIaXXylK9xTOLijEqSemDN3AeXa6e7C3HC88x5gfLMRXiSAj
    sonar_api_key: AgBNFSt84QFRiGK2QAyRnzJf9EzycT0UQ7hIgLlt/gq7nWkzmRLNWbV9Pgf/xMvqKQz/LkdvvSHeCD1OSebHiXIwExBBegU1Hj76w6td1vNJDx1ophRKlr6fZYPJ940IMcz/8Isk5iioCCZDhdENlbS1FRBADXrbfHepssibgDGDoA5dCUd7P21ZMGiil5lAH+gBle8g9sdK3kd4tSAmAszgiScIgg2d/WhYETARAzEwiMxnLIWpuhXn8FxwymigVrCgzyRBVg9NX5nzQNZpnBG7CVSpYNecm5VElZTWNCZUV4eXN0MfR9S7P7KD0VarBg3ZBE63+sZ1iud4KTTucpwEqXjNImm1o1BBPRYQqzTjUo/LKfmirAIUQnoZ8C3YeyOrU0zmQYT3zbhHolhDwD8dqnZiqM6d3npOzUHOqdyBjs6pFySChZ4ANx0bkSVCW4SAkt5Ha6VJSiUS/V7aKmcvhvQDwc5/HXpdvv7Q0DSsXkEfCiY0MCYxrtS9BDt2DVYoRNdrNoH7+3IyGFISGEJRcJmnoshgzHoFcQUUOdlAv2e/6AAcX9kmaa3gO4MLPxHSsnUrBcqh3Y/GJs0LsYbC2SnIdD1uZ5TaB+jbphXytCoO8mYP7GevF8B9xOfiy/cfH44BCCPGZB9H1hVqtWGDYqyg90m1FnTxlZZvcBIzO6inqxiBv+IfuM2T+8NhHspmZeANlsEt0P0jP4KwS/amvQDPO6T563cb96fFoT+wKXXQoYSlCL01LjOQtQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: api-secret
      namespace: devin-dashboard
---
