apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: api-secret
  namespace: devin-dashboard
spec:
  encryptedData:
    confluence_api_key: AgCjsQ4h4o2VQZFo4bBbJe+pp8dR6zJycExDaL/qKkz41u4XIFg+lWDgKZLI5+et3NNEHL7o9Bnl1aE8Vjf9iwtFUXBMEZ1HpNv4Xl1+6BzH59wqZP8SLj4OozXahOIqFAXMne20gYr8ZXgtEiHR11HBRdqEL0iNrGOuwwhFtwptNVDg50EGehNBtlv6TmUNNbr16RTbpsoJfTallNsOyeohYrq6KBjcRiNSB9juEwi4NXCxRVvpsKjGUQf/CCJyxxl+JTY7f2t4HPNdnOrQygOjUMNt8kNhPYz9JidYEjCcKkB+7msN5bb791cBUxJDaPUB/9ESanM64yQGlaV8s2mtp0paPnpqUP2Uf/EIyolOvOkHVOUvK4oRIDmTrT93yVdaDRqIz1ts78IWH4ewwett3mg+gasxy4XofAxS3Gkaw6ZEGbsWUAXFdlINewOY5HqPZUBq9SG/GXk/s7IlZsb2QQEIEKnx556Xv2mMvQFz3nbvE9HtjigWlqApN8vR0Psof98Loj2jL3FtRWfqjdOfc/PP8yRYyq7Y5JXZ8bcvChJhqJGGq9XCaE30U2Eclymso+jUHI9JHUl+ywjHfnfD+kAlUjN+HKd73u9Iyf1lWnu42HoNiQ28s869VjeHCWlBUx4RqcRRm5tqQHv2RX9EH+xGLKXr4b1ofESMD2UmxVtHLRl68N0XAN0TtVs8bgFHeJ2mhUejXKLx/Zn/uKFEERLFuCA4XhOpzETytOw6KFl5F9Xmf3tuKOAvIzqLwzbipkmOdstSzAD7HWBC9c4m6bz8qt7UQv9lenBvvlsWVDQeK8fSvLyAWXT4R1FZLNEpCAoXk/r5JBOVgcU9V11tGi02fQ/mb4snMh2F+HDO7VZBkHLBYTICXr9f1vb8+NmeaF7MDBTy5rPCdbQZcG25G/lvaoKyS3WzQEGmbS56UM07YKwZbq2pEFSoCxIqsaC9izYN/3Akin6mEeHdnWn/A3HIix0Pyg==
    sonar_api_key: AgAh+HcxzS0Cy4xEFvILlaH5Z7HVfTwYT/uj7JKvzpCwKOuh0WxQisZVT3PWFrRO+UIcm5FBrsMYWmSwloMxNjnYwknmPUpD9XGI5sO36cBMeJ1yC671xsfiE+tWfDUp6DqNJYn0X4B1aM2V2kxJMoSis6qS+VARSAa8SaFO4MSjk64t9wWYf44btUmjvjIbIK+u+kuSHjnYm7MPJwlEHz0xFuP4IOLQk9vBTpUxLT6kq9si/UmLLKav3I679u9Olw4SFWKVTYcFjQtqi5FwcApJiKZZ4d/0+4cYYB0/QWWFbpR7YyTEA6ekphEkjsc9LJb1xS0biKCpJ/JBKL9CvATmh9AqJQLB9iCFzIRcCojJXFslHWpjWzSOpMYhSKlL7xwA3XC/tSQ5+D9u0WH1H7sjb3rRRpwwq3vS8jphzCOHEvDSCjzu/6q5qhENjECG0IE8Vt8Up+ZvTELGLeKGFlXV5Q3tLxqDrg2Zg4tJFg69aKgQxnzwsF/shUDXSRIBRgJtTTvG9BMTnIuVjMN0TkgTTILRB8SZPtqXx1NqYt3t1cKDD2itnrI0UsXYQa/1xtmZedCuERXNaTLWRcUTtAY9JHUSSsKJXrcU8NImoJp1M1ON39bS1B0K7MQsMWZ7xoOaApEpSHDtiQOzq/82OtpC1XOwxaFGU6IDJuiw1XxtZX8LwaKSRta/nNQ5GXgc7Kg5UpOPm9gURS5m5kaV1dNBQdVs0XBDUfaWxW2WtGm6Ss5ga6IbOlZFJyfnEA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: api-secret
      namespace: devin-dashboard
---
